### ISSUE TITLE
Unable to install the module into prestashop ver 1.7.2.4

### ISSUE THREAD

**Issue by jackieyap79** [sarjon/gamifications#1]
Dear Gamifications team,

Good day, for your kind information, I'm having problem after download the zip, and try to install through the prestashop module installer, the system replied the zip may not contain the valid module file.

I read your instruction to compose install, which I don't understand what it mean. 

Looking forward your assist and help.
At the same time, I would like to say thank you to all your effort to make this available in prestashop version 1.7.xx

Thank you.

Best Regards,
Jackie Yap

**Comment by sarjon** [comment]
Hi @jackieyap79, you have to generate autoloader for module using Composer. You can download composer here: https://getcomposer.org/

Module was made for PrestaShop 1.7.0.0 and thus not tested on higher versions of PS.
