### ISSUE TITLE
Install directly

### ISSUE THREAD

**Issue by genocide87** [sarjon/gamifications#2]
Hello,

If i dont' have any possibility to git clone this module, how can I add it to my PS 1.7? There's another solution?

**Comment by sarjon** [comment]
Hi,

you may download module via "Download ZIP". See here https://screenshots.firefox.com/e68JiTG7HRScjPEs/github.com

However, you will still need to generate some files manually using `composer` command line tool or you may try this GUI tool https://www.getcomposercat.com/ to do that.

**Comment by genocide87** [comment]
Thx for the fast answer!

I downloaded the composer but, when I try to create somethign I receive the "composer unavailable" message.

I add the zip then all is blocked....

What I have to do? :/

**Comment by sarjon** [comment]
Assuming you are on Windows, you can follow this to install composer: https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by genocide87** [comment]
![image](https://user-images.githubusercontent.com/40593235/41903727-fd141abc-7936-11e8-884f-e4fc0aa5af07.png)

Ok, I'm here and now I click on the install all packages. What I miss now? Where I can find it after the install? :)

**Comment by sarjon** [comment]
Once you run composer, some files should be generated in `D:\..\gamifications\vendor\` folder. Please check if you you see `autoload.php`, if so, you are good to go. Then move `gamifications` directory to your PrestaShop `modules/` folder and install it from Back Office.

**Comment by genocide87** [comment]
WAAAAAAAAAAAAAAAAAAAAAAAAAAA!!


<3 thank you master!!

**Comment by genocide87** [comment]
T_T Why I don't see it into the modules section of PS?

I'm using PrestaShop: 1.7.2.4
